### ISSUE TITLE
tenant url gets constructed incorrectly.

### ISSUE THREAD

**Issue by pbnj** [britive/python-cli#14]
`pybritive login` command fails with error (replaced `tenant` name with `[redacted]`):

```
$ pybritive login

Credentials for tenant https://[redacted].britive-app.com not found.
Performing interactive login against tenant https://[redacted].britive-app.com
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1055ac0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //[redacted].britive-app.com.britive-app.com/api/auth/cli/retrieve-tokens (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1055ac0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/cli_interface.py", line 19, in safe_cli
    cli()
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/helpers/build_britive.py", line 32, in wrapper
    return f(ctx=ctx, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/commands/login.py", line 15, in login
    ctx.obj.britive.login(explicit=True)
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/britive_cli.py", line 78, in login
    token=self.credential_manager.get_token(),
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/helpers/credentials.py", line 119, in get_token
    self.perform_interactive_login()  # will write the credentials out and update self.credentials as needed
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/helpers/credentials.py", line 66, in perform_interactive_login
    response = self.retrieve_tokens()
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/helpers/credentials.py", line 98, in retrieve_tokens
    return requests.post(url, headers=headers, json=auth_params)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //[redacted].britive-app.com.britive-app.com/api/auth/cli/retrieve-tokens (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1055ac0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pybritive", line 8, in <module>
    sys.exit(safe_cli())
  File "/opt/homebrew/lib/python3.10/site-packages/pybritive/cli_interface.py", line 21, in safe_cli
    raise click.ClickException(str(e)) # from None
click.exceptions.ClickException: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //[redacted].britive-app.com.britive-app.com/api/auth/cli/retrieve-tokens (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1055ac0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

Specifically, this part where the CLI is trying to reach `<tenant>.britive-app.com.britive-app.com/api/auth/cli/retrieve-tokens`: 

```
Max retries exceeded with url: //[redacted].britive-app.com.britive-app.com/api/auth/cli/retrieve-tokens (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1055ac0a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'
```

**Comment by twratl** [comment]
The tenant value for `pybritive` is just the subdomain. If the tenant is `example.britive-app.com` then the tenant would be configured in `pybritive` as `example`. 

You can import the existing NPM config as well: `pybritive configure import`.

I will ensure that any tenant value provided in `configure` is properly stripped of `.britive-app.com` before persisting to the config file. Thanks for pointing this out.

**Comment by twratl** [comment]
`v0.2.0` properly strips  `.britive-app.com` from the user input. `v0.2.1` fixes a couple other bugs. Can you upgrade and see if that resolves your issue? You may need to clear your `~/.britive/pybritive.config` file if it still holds the prior values.
